### ISSUE TITLE
File meta information with zero length

### ISSUE THREAD

**Issue by ibaryshnikov** [Enet4/dicom-rs#27] opened 2019-12-16 15:32 UTC
I have a case with `Tag(0x0002, 0x0001)`, `VR: OB`, and `Length(0)`. Is it a correct case? I haven't found a corresponding page in the standard so far.

**Comment by Enet4** [comment] 2019-12-16 17:01
This is heavily related with #28. I have left a comment on this subject there. The way I see it, that is a non-compliant DICOM file.

**Comment by Enet4** [comment] 2020-04-17 09:55
I will close this as a duplicate of #28. Nevertheless, new issues can be posted if additional cases of missing meta-data are found in the wild.

**Closed by Enet4** 2020-04-17 09:55 UTC
