### ISSUE TITLE
toimage command line utility error - panics on LUT value processing

### ISSUE THREAD

**Issue by MountainAndMorning** [Enet4/dicom-rs#346] opened 2023-05-13 01:58 UTC
I try to use the toimage command line utility with the attached dicom file but get the error below:
```bash
(base) liangwanyou@liangwanyoudeMacBook-Air toimage % cargo run /Users/liangwanyou/Desktop/d/1.2.840.113704.7.1.1.8340.1491789704.637.dcm
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `/Users/liangwanyou/Downloads/dicom-rs-master/target/debug/dicom-toimage /Users/liangwanyou/Desktop/d/1.2.840.113704.7.1.1.8340.1491789704.637.dcm`
thread '<unnamed>' panicked at 'assertion failed: (index as usize) < self.table.len()', pixeldata/src/lut.rs:300:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'assertion failed: (index as usize) < self.table.len()', pixeldata/src/lut.rs:300:9
thread '<unnamed>' panicked at 'assertion failed: (index as usize) < self.table.len()', pixeldata/src/lut.rs:300:9
thread '<unnamed>' panicked at 'assertion failed: (index as usize) < self.table.len()', pixeldata/src/lut.rs:300:9
thread '<unnamed>thread '' panicked at '<unnamed>assertion failed: (index as usize) < self.table.len()' panicked at '', assertion failed: (index as usize) < self.table.len()pixeldata/src/lut.rs', :pixeldata/src/lut.rs300::3009:
9
.
.
.
thread '<unnamed>' panicked at 'assertion failed: (index as usize) < self.table.len()', pixeldata/src/lut.rs:300:9
thread '<unnamed>' panicked at 'assertion failed: (index as usize) < self.table.len()', pixeldata/src/lut.rs:300:9
(base) liangwanyou@liangwanyoudeMacBook-Air toimage % 

```
[1.2.840.113704.7.1.1.8340.1491789704.637.dcm.zip](https://github.com/Enet4/dicom-rs/files/11468638/1.2.840.113704.7.1.1.8340.1491789704.637.dcm.zip)

**Comment by Enet4** [comment] 2023-05-13 14:43
Thank you very much for reporting this bug, @MountainAndMorning! This was caused by the file's _Pixel Data_ filling in the pixel data values beyond the bits effectively reserved for imaging data (bits stored is 12 in the example, but the 4 high bits would occasionally be set to 1). This is technically allowed, according to the standard, but was not always considered here. I have just patched this in #347.

**Comment by MountainAndMorning** [comment] 2023-05-14 04:36
Thanks for your help. I have another stupid question. How can I update dicom-rs to this patched version.

**Comment by Enet4** [comment] 2023-05-14 08:40
> How can I update dicom-rs to this patched version.

You can temporarily [specify the dependency](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories) as coming from the git branch containing the patch. I might work on publishing the patch at some point later.

```toml
[dependencies]
dicom_pixeldata = { git = "https://github.com/Enet4/dicom-rs.git", branch = "bug/346" }

```

A note of warning though, there are some breaking changes from past merged contributions.

**Comment by MountainAndMorning** [comment] 2023-05-14 14:05
Great! Thank you very much.

**Closed** 2023-05-29 10:42 UTC
Labels: bug, A-lib, C-pixeldata
