### ISSUE TITLE
Can't read unknown Tag

### ISSUE THREAD

**Issue by mightymouse2045** [Enet4/dicom-rs#115] opened 2021-04-26 03:13 UTC
(1001,041e) ST [Date: 20210212025552[^]Date: 20210217033201[^]Date: 20210226002420[^]] #  70, 1 Unknown Tag & Data

Attempting to read in rust fails with:
Error: ParseMetaDataSet { source: UndefinedValueLength { tag: Tag(0x0022, 0x0016), backtrace: Backtrace(()) } }

dcmtk - dcmdump works fine to read the above tag which is where the line came from above.

**Comment by mightymouse2045** [comment] 2021-04-26 04:21
Update - sorry this is actually related to the DICOM files being used. Depending on the file I get the above error unrelated to the tag I specified in the above comment.

Also I get a failed to fill whole buffer error on others, but have no problem reading the same files with dcmtk dcmdump

**Comment by Enet4** [comment] 2021-04-26 08:39
Could you provide a minimal example of the code which you were trying?

Still, I suspect that the problem is equivalent to #83. `open_file` can only open complete DICOM files with preamble and file meta group. In order to read a simple DICOM data set, you would need to use [one of the `InMemDicomObject::read_dataset`](https://github.com/Enet4/dicom-rs/blob/master/object/src/mem.rs#L137-L187) functions, which are available upstream (#84) but not released yet.

**Comment by Enet4** [comment] 2021-07-22 21:34
Closing as a duplicate of #83, as it is very likely that caused by an attempt to read a file without a preamble, which in this case needs to be done with separate methods. Please file a new issue with a concrete example if the problem persists.

**Closed by Enet4** 2021-07-22 21:34 UTC
Labels: duplicate, question
