### ISSUE TITLE
Handling empty date

### ISSUE THREAD

**Issue by ibaryshnikov** [Enet4/dicom-rs#11] opened 2019-09-13 13:17 UTC
Sometimes the date in DICOM file is `0000-00-00`. Is it a common case in the ecosystem when the date is empty?

**Comment by neandrake** [comment] 2019-09-13 20:58
It is fairly common for date elements to either be all zeros, empty, or not present altogether. Including SeriesDate / StudyDate.

**Comment by pauldotknopf** [comment] 2019-09-14 00:11
This kind of relates to #9. We shouldn't attempt to parse the VR's while loading the DICOM files.

IMO, all parsing should be done after the fact, for example, using ```Result<[u8]>``` for ```VR::IS```, or ```Result<DateTime>``` for ```VR::DT```.

@Enet4, what do you think about making this the "default" approach?

**Comment by Enet4** [comment] 2019-09-14 17:05
As mentioned in #9, it is reasonable to preserve textual values as strings when loading DICOM objects and only convert when requested. I am not opposed to making this the default, especially since some equipment and software out there have the poor habit of writing values which may not 100% DICOM compliant.

Regarding this issue (and others of similar nature), it helps if you can make a reproducible example, so that it can be independently reasoned with and tested. In part, this also means that there should be an easy way to build and write DICOM objects, yet to be worked on.

**Comment by Enet4** [comment] 2020-05-24 15:17
Closing this as partially resolved by #24, and for discussion to continue in #9.

**Closed by Enet4** 2020-05-24 15:17 UTC
