### ISSUE TITLE
use dicom-rs with wasm bindgen

### ISSUE THREAD

**Issue by vampolo** [Enet4/dicom-rs#39] opened 2020-05-18 18:02 UTC
Hey,

I'm trying to use `dicom-rs` with wasm bindgen for a subassembly app. So far I have something like this function to load a dicom file using JS fetch

```
pub async fn load_url(url: String) -> Result<(), JsValue> {
    let mut opts = RequestInit::new();
    opts.method("GET");
    opts.mode(RequestMode::Cors);

    let request = Request::new_with_str_and_init(&url, &opts)?;

    let window = web_sys::window().unwrap();
    let resp_value = JsFuture::from(window.fetch_with_request(&request)).await?;

    // `resp_value` is a `Response` object.
    assert!(resp_value.is_instance_of::<Response>());
    let resp: Response = resp_value.dyn_into().unwrap();

    // Convert this other `Promise` into a rust `Future`.
    let array_buffer = JsFuture::from(resp.array_buffer()?).await?;

    let typebuf: js_sys::Uint8Array = js_sys::Uint8Array::new(&array_buffer);

    let mut slice = vec![0; typebuf.length() as usize];
    typebuf.copy_to(&mut slice[..]);

    let mut file = Cursor::new(slice);

    let obj = from_reader(&mut file).unwrap();

    // let patient_name = obj.element_by_name("PatientName").unwrap().to_str().unwrap();

    // console::log_1(&patient_name.to_string().into());

    Ok(())
}
```

Problem is the line `let obj = from_reader(&mut file).unwrap()` fails with :

![image](https://user-images.githubusercontent.com/294496/82244976-fb142680-98f6-11ea-9b7c-e27513f1a14d.png)

I'm using the latest master. Not sure if the function I'm calling on the dicom-rs side is the right one. The import is the following: `use dicom_object::from_reader;`

**Comment by Enet4** [comment] 2020-05-18 18:26
Thank you for the example! `from_reader` does not expect a preamble, which is probably what made the operation fail. Can you try and skip the first 128 bytes before calling `from_reader`?

I agree that the ergonomics of this API can be improved here. At some point the options builder pattern might be more interesting.

**Comment by vampolo** [comment] 2020-05-18 21:05
Thank you @Enet4 

Yeah dropping the first 128 bytes did it

```
    let mut file = Cursor::new(&slice[128..]);

    let obj = from_reader(&mut file).unwrap();

    let patient_name = obj.element_by_name("PatientName").unwrap().to_str().unwrap();

    console::log_1(&patient_name.to_string().into());
```

**Comment by Enet4** [comment] 2020-05-24 15:28
Closing, as the main concern appears to have been resolved, and the current behavior of the API is by design. Improvements to the API can be suggested in #43.

**Closed by Enet4** 2020-05-24 15:28 UTC
