### ISSUE TITLE
Request for feature: file-sets

### ISSUE THREAD

**Issue by JohnScience** [Enet4/dicom-rs#319] opened 2022-12-10 20:59 UTC
[`pydicom`](https://pydicom.github.io/pydicom/stable/) package already offers support for [file-sets](https://pydicom.github.io/pydicom/dev/tutorials/filesets.html).

I would love to work in Rust on my project, yet for now I have to use Python instead.

**Comment by Enet4** [comment] 2022-12-10 21:22
Hello @JohnScience, that would be what I pictured in #184. Nomenclature aside (this DicomDir abstraction could totally be called a file set), it's pretty much the same idea. With that said, a pull request with a proposal for this API would be welcomed!

Duplicate of #184. We can continue talking from there if you wish to give it a try and/or receive guidance on the matter.

**Closed by Enet4** 2022-12-10 21:22 UTC

**Comment by JohnScience** [comment] 2022-12-11 19:07
@Enet4 Due to deadlines and insufficient knowledge of the domain, I don't think this investment is worthwhile this time. However, I'll be glad to join your effort if our project takes off. Wish you success with `dicom-rs`!
